import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage();
const errs=[];
page.on('pageerror', e=>errs.push('PAGEERR: '+e.message));
page.on('console', m=>{ if(m.type()==='error') errs.push('CONSOLE: '+m.text()); });
await page.goto('http://localhost:5173/', {waitUntil:'networkidle'});
await page.waitForTimeout(500);
const speed0 = await page.textContent('#hSpeed');
await page.keyboard.down('e');
await page.waitForTimeout(1200);
await page.keyboard.up('e');
await page.waitForTimeout(100);
const speed1 = await page.textContent('#hSpeed');
const gear1  = await page.textContent('#hGear');
await page.waitForTimeout(1500);
const speed2 = await page.textContent('#hSpeed');
console.log('errors:', errs.length? errs.join('\n') : '(none)');
console.log('speed before:', speed0, '| while driving:', speed1, 'gear', gear1, '| after coast:', speed2);
await browser.close();
